// FAQ page -- static, like privacy.js/terms.js: site-i18n.js only, one
// data-i18n-html key per question (a <details> element's whole content:
// its <summary> question and the answer), so the two languages stay easy
// to keep aligned. Answers that need a person end in a link to
// support.html, with ?topic= preselecting the form's topic.

const q = (question, answer) => `<summary>${question}</summary><div class="faq-answer">${answer}</div>`;

const FAQ_I18N = {
  en: {
    'nav.login': 'Log in',
    'nav.faq': 'FAQ',
    'nav.support': 'Contact support',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms of Service',
    'faq.title': 'Frequently asked questions',
    'faq.intro': "Can't find your answer? <a href=\"support.html\">Contact support</a> - we're happy to help.",
    'faq.groupPlans': 'Plans & billing',
    'faq.groupAccount': 'Account & data',
    'faq.groupHelp': 'Help',
    'faq.plans': q('What do I get with Pro?',
      '<p>The free plan has up to 10 one-off tasks, 5 recurring tasks and 5 notes per task. Pro removes those limits and the subscription reminders in your list. See the current prices on our <a href="landing.html#pricing">pricing page</a>.</p>'),
    'faq.trial': q('Is there a free trial?',
      '<p>Yes: a new account can try Pro free for 14 days, without entering payment details. Each account gets one trial, and only if it has never had a plan before.</p>'),
    'faq.cancel': q('How do I cancel my subscription?',
      '<p>In the app, open <strong>Settings</strong> and choose <strong>Cancel subscription</strong> (or <strong>Manage billing…</strong>, which opens Stripe\'s own billing page). You keep Pro until the end of the period you\'ve already paid for, and nothing more is charged.</p>'),
    'faq.resume': q('I cancelled - can I change my mind?',
      '<p>Yes, any time before your paid period ends: <strong>Settings</strong> → <strong>Resume subscription</strong>. It renews again at the end of that period, as if you had never cancelled. Nothing is charged until then - so please don\'t subscribe again, just resume.</p>'),
    'faq.receipts': q('Where is my receipt?',
      '<p>After every payment we email you a fiscalized receipt, as Croatian law requires. If you can\'t find it, check your spam folder, or <a href="support.html?topic=billing">ask us</a> to send it again.</p>'),
    'faq.refunds': q("I was charged when I didn't expect it. Can I get a refund?",
      '<p><a href="support.html?topic=billing">Contact support</a> and tell us which payment it is. If you were charged by mistake - for example twice for the same period - we refund it to your card, or, if you prefer, extend your subscription by the time you\'ve paid for.</p>'),
    'faq.priceChanges': q('Will my price change?',
      '<p>Your subscription keeps renewing at the price you subscribed at. If we ever need to change the price of existing subscriptions, we\'ll tell you well in advance - see the <a href="terms.html">Terms of Service</a>.</p>'),
    'faq.anchor': q('What is the price with the anchor (⚓) next to it?',
      '<p>That\'s the anchor price ("sidrena cijena"): Croatian law requires every price to be shown together with the regular price it had on 10 September 2026, so you can see how it has changed. It isn\'t what you pay unless it equals the price itself. Our full price list, including earlier versions, can be downloaded on the <a href="landing.html#pricing">pricing page</a>.</p>'),
    'faq.verify': q("I didn't get the verification email.",
      '<p>Check your spam folder first. The link is valid for 6 hours - if it has expired or never arrived, simply register again with the same email address and we\'ll send a new one. Still nothing? <a href="support.html?topic=account">Contact support</a>.</p>'),
    'faq.password': q('I forgot my password.',
      '<p>On the login screen, choose <strong>Forgot password?</strong> and enter your email address. We\'ll send you a link to set a new password; it\'s valid for 30 minutes and works once.</p>'),
    'faq.changeEmail': q('How do I change my login email?',
      '<p>In <strong>Settings</strong>, choose <strong>Change email…</strong>. We send a confirmation link to the new address; your old address gets a link to undo the change, in case it wasn\'t you.</p>'),
    'faq.export': q('Can I get a copy of my data?',
      '<p>Yes - in <strong>Settings</strong>, <strong>Download my data…</strong> gives you all your tasks and notes at any time.</p>'),
    'faq.delete': q('What happens when I delete my account?',
      '<p>Your tasks, notes and settings are deleted immediately. For 12 months we keep only your email address, a hashed password and whether you\'ve had a trial or subscription - see the <a href="privacy.html">Privacy Policy</a> for why. If you have a paid subscription, you can also schedule the deletion for when it ends.</p>'),
    'faq.bug': q('Something isn\'t working, or I have an idea.',
      '<p>We\'d love to hear it. <a href="support.html?topic=bug">Report a bug</a> or <a href="support.html?topic=feature">suggest a feature</a> - for a bug, tell us what you did, what you expected and what happened instead.</p>'),
    'faq.other': q('How can I make a complaint?',
      '<p>Use the <a href="support.html?topic=complaint">support form</a> and choose <em>Complaint</em>. We confirm every complaint and answer it in writing within 15 days.</p>'),
  },
  hr: {
    'nav.login': 'Prijava',
    'nav.faq': 'Česta pitanja',
    'nav.support': 'Kontakt podrške',
    'nav.privacy': 'Pravila privatnosti',
    'nav.terms': 'Uvjeti korištenja',
    'faq.title': 'Česta pitanja',
    'faq.intro': 'Niste pronašli odgovor? <a href="support.html">Kontaktirajte podršku</a> - rado ćemo pomoći.',
    'faq.groupPlans': 'Planovi i naplata',
    'faq.groupAccount': 'Račun i podaci',
    'faq.groupHelp': 'Pomoć',
    'faq.plans': q('Što dobivam s Pro planom?',
      '<p>Besplatni plan ima do 10 jednokratnih zadataka, 5 ponavljajućih zadataka i 5 bilješki po zadatku. Pro uklanja ta ograničenja i podsjetnike za pretplatu s vašeg popisa. Trenutne cijene pogledajte na našoj <a href="landing.html#pricing">stranici s cijenama</a>.</p>'),
    'faq.trial': q('Postoji li besplatno probno razdoblje?',
      '<p>Da: novi račun može besplatno isprobati Pro 14 dana, bez unosa podataka za plaćanje. Svaki račun ima jedno probno razdoblje, i to samo ako nikad prije nije imao plan.</p>'),
    'faq.cancel': q('Kako otkazati pretplatu?',
      '<p>U aplikaciji otvorite <strong>Postavke</strong> i odaberite <strong>Otkaži pretplatu</strong> (ili <strong>Upravljaj plaćanjem…</strong>, koje otvara Stripeovu stranicu za naplatu). Pro zadržavate do kraja već plaćenog razdoblja, a ništa se više ne naplaćuje.</p>'),
    'faq.resume': q('Otkazao/la sam - mogu li se predomisliti?',
      '<p>Da, bilo kad prije isteka plaćenog razdoblja: <strong>Postavke</strong> → <strong>Nastavi pretplatu</strong>. Na kraju tog razdoblja ponovno se obnavlja, kao da je niste ni otkazali. Do tada se ništa ne naplaćuje - zato se nemojte ponovno pretplaćivati, samo je nastavite.</p>'),
    'faq.receipts': q('Gdje je moj račun?',
      '<p>Nakon svakog plaćanja e-mailom vam šaljemo fiskalizirani račun, kako zahtijeva hrvatski zakon. Ako ga ne možete pronaći, provjerite mapu neželjene pošte ili nas <a href="support.html?topic=billing">zamolite</a> da ga pošaljemo ponovno.</p>'),
    'faq.refunds': q('Naplaćeno mi je nešto što nisam očekivao/la. Mogu li dobiti povrat?',
      '<p><a href="support.html?topic=billing">Kontaktirajte podršku</a> i navedite o kojem se plaćanju radi. Ako vam je naplaćeno greškom - na primjer dvaput za isto razdoblje - vraćamo novac na vašu karticu ili, ako vam je draže, produljujemo pretplatu za vrijeme koje ste platili.</p>'),
    'faq.priceChanges': q('Hoće li mi se cijena promijeniti?',
      '<p>Vaša se pretplata obnavlja po cijeni po kojoj ste se pretplatili. Ako ikad budemo morali promijeniti cijenu postojećih pretplata, obavijestit ćemo vas dovoljno unaprijed - pogledajte <a href="terms.html">Uvjete korištenja</a>.</p>'),
    'faq.anchor': q('Koja je to cijena sa sidrom (⚓) pokraj?',
      '<p>To je sidrena cijena: hrvatski zakon zahtijeva da se uz svaku cijenu istakne i redovna cijena koja je vrijedila 10. rujna 2026., kako biste vidjeli kako se mijenjala. To nije cijena koju plaćate, osim ako je jednaka samoj cijeni. Cijeli naš cjenik, uključujući ranije verzije, možete preuzeti na <a href="landing.html#pricing">stranici s cijenama</a>.</p>'),
    'faq.verify': q('Nije mi stigao e-mail za potvrdu.',
      '<p>Najprije provjerite mapu neželjene pošte. Poveznica vrijedi 6 sati - ako je istekla ili nikad nije stigla, jednostavno se ponovno registrirajte s istom e-mail adresom i poslat ćemo novu. I dalje ništa? <a href="support.html?topic=account">Kontaktirajte podršku</a>.</p>'),
    'faq.password': q('Zaboravio/la sam lozinku.',
      '<p>Na zaslonu za prijavu odaberite <strong>Zaboravili ste lozinku?</strong> i upišite svoju e-mail adresu. Poslat ćemo vam poveznicu za postavljanje nove lozinke; vrijedi 30 minuta i može se iskoristiti jednom.</p>'),
    'faq.changeEmail': q('Kako promijeniti e-mail za prijavu?',
      '<p>U <strong>Postavkama</strong> odaberite <strong>Promijeni e-poštu…</strong>. Na novu adresu šaljemo poveznicu za potvrdu, a na staru poveznicu za poništavanje promjene, za slučaj da je niste vi zatražili.</p>'),
    'faq.export': q('Mogu li dobiti kopiju svojih podataka?',
      '<p>Da - u <strong>Postavkama</strong> <strong>Preuzmi moje podatke…</strong> u bilo kojem trenutku daje sve vaše zadatke i bilješke.</p>'),
    'faq.delete': q('Što se događa kad izbrišem račun?',
      '<p>Vaši zadaci, bilješke i postavke odmah se brišu. Sljedećih 12 mjeseci čuvamo samo vašu e-mail adresu, hashiranu lozinku i podatak jeste li imali probno razdoblje ili pretplatu - zašto, pogledajte u <a href="privacy.html">Pravilima privatnosti</a>. Ako imate plaćenu pretplatu, brisanje možete i zakazati za trenutak kad istekne.</p>'),
    'faq.bug': q('Nešto ne radi ili imam ideju.',
      '<p>Rado ćemo čuti. <a href="support.html?topic=bug">Prijavite grešku</a> ili <a href="support.html?topic=feature">predložite novu mogućnost</a> - za grešku nam opišite što ste napravili, što ste očekivali i što se dogodilo umjesto toga.</p>'),
    'faq.other': q('Kako mogu podnijeti prigovor?',
      '<p>Upotrijebite <a href="support.html?topic=complaint">obrazac za podršku</a> i odaberite <em>Prigovor</em>. Svaki prigovor potvrđujemo i na njega pisano odgovaramo u roku od 15 dana.</p>'),
  },
};

initSitePage(FAQ_I18N);
